apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "6"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"homework"},"name":"geektime-deployment","namespace":"default"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"homework"}},"template":{"metadata":{"labels":{"app":"homework"}},"spec":{"containers":[{"command":["ls","-al","/data"],"image":"centos","name":"centos","volumeMounts":[{"mountPath":"/data/","name":"app-volume"}]}],"initContainers":[{"command":["cp","/data/main","/app"],"image":"k8s.gcr.io/busybox","name":"cpmain","volumeMounts":[{"mountPath":"/app","name":"app-volume"},{"mountPath":"/data","name":"data-volume"}]}],"volumes":[{"emptyDir":{},"name":"app-volume"},{"hostPath":{"path":"/data/homework4"},"name":"data-volume"}]}}}}
  creationTimestamp: "2022-06-07T10:39:52Z"
  generation: 6
  labels:
    app: homework
  name: geektime-deployment
  namespace: default
  resourceVersion: "2168546"
  uid: 489be166-fddd-4481-b9e2-19db8a4874c4
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: homework
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: homework
    spec:
      containers:
      - command:
        - /data/homework3
        image: centos
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - ls
            - /data/homework3
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: centos
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: 8888
            scheme: HTTP
          initialDelaySeconds: 30
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 35
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 250m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /data/
          name: app-volume
      dnsPolicy: ClusterFirst
      initContainers:
      - command:
        - cp
        - /data/homework3
        - /app
        image: k8s.gcr.io/busybox
        imagePullPolicy: Always
        name: cpmain
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app
          name: app-volume
        - mountPath: /data
          name: data-volume
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: app-volume
      - hostPath:
          path: /data/homework4
          type: ""
        name: data-volume
